### ISSUE TITLE
Undefined symbol: mac_addr_dlpi

### ISSUE THREAD

**Issue by Belippo** [slytechs-repos/jnetpcap-legacy#7]
Jnetpcap v1.4 works well in windows but when i run the same code (i send a simple syn tcp packet) in Linux amd64 i got the error:
`Undefined symbol: mac_addr_dlpi`

**Comment by Belippo** [comment]
Oh ok. So should you correct and recompile to fix the bug?

**Comment by slytechs-repos** [comment]
I'm having trouble recompiling from source right now. I am not sure you would have any more luck. Its been many years since I've had to touch this code, but it needs to be done/refreshed for latest everything.

For now I would suggest you no use PcapUtils.getHardwareAddress and use the JDK API https://docs.oracle.com/javase/7/docs/api/java/net/NetworkInterface.html#getHardwareAddress() until I fix this.

**Comment by Belippo** [comment]
Ok without that function it works! 
Thank you, i really appreciate your support, so available...Keep it up. JNETPcap is the only updated API in java as i see. As final user i can suggest to provide high level method to craft and send packets. Keep me update if you can recompile

**Comment by slytechs-repos** [comment]
> provide high level method to craft and send packets

This functionality is coming, again in [jNetPcap Pro](https://github.com/slytechs-repos/jnetpcap-pro). 

[jNetPcap v2](https://github.com/slytechs-repos/jnetpcap) module is pure libpcap functionality. jNetPcap Pro is the high level protocol extension to jNetPcap which adds all of the higher level functionality. This separation allows greater stability for the libpcap API and to be independent of new features which are provided by the rest of the modules.

The jNetPcap v1 (legacy) is only supported for bug fixes and won't get any additional features. When you can, I would suggest you start integrating with v2 API.

 I hope that explains it.
